version: '3.8'

services:
  pywhatsweb:
    build: .
    container_name: pywhatsweb
    volumes:
      - ./whatsapp_data:/app/whatsapp_data
      - ./examples:/app/examples
    environment:
      - WHATSAPP_HEADLESS=true
      - WHATSAPP_DEBUG=true
      - WHATSAPP_LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: ["python", "-m", "pywhatsweb.cli", "--listen"]
    
  pywhatsweb-dev:
    build: .
    container_name: pywhatsweb-dev
    volumes:
      - .:/app
      - ./whatsapp_data:/app/whatsapp_data
    environment:
      - WHATSAPP_HEADLESS=false
      - WHATSAPP_DEBUG=true
      - WHATSAPP_LOG_LEVEL=DEBUG
    ports:
      - "8001:8000"
    stdin_open: true
    tty: true
    command: ["python", "-m", "pywhatsweb.cli", "--qr-only"]
    
  pywhatsweb-test:
    build: .
    container_name: pywhatsweb-test
    volumes:
      - .:/app
    environment:
      - WHATSAPP_HEADLESS=true
      - WHATSAPP_DEBUG=false
    command: ["python", "-m", "pytest", "tests/", "-v"]
