[tox]
envlist = py38, py39, py310, py311, py312, lint, format
isolated_build = True

[testenv]
deps =
    -r requirements.txt
    -r requirements-dev.txt
commands =
    pytest {posargs:tests/} --cov=pywhatsweb --cov-report=term-missing --cov-report=html

[testenv:lint]
deps =
    -r requirements-dev.txt
commands =
    black --check pywhatsweb tests examples
    isort --check-only pywhatsweb tests examples
    flake8 pywhatsweb tests examples
    mypy pywhatsweb

[testenv:format]
deps =
    -r requirements-dev.txt
commands =
    black pywhatsweb tests examples
    isort pywhatsweb tests examples

[flake8]
max-line-length = 88
extend-ignore = E203, W503
exclude = .git,__pycache__,build,dist,*.egg-info

[isort]
profile = black
multi_line_output = 3
line_length = 88

[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
