blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/llongaray/pywhatsweb/discussions
    about: Please ask and answer questions here.
  - name: Email Support
    url: mailto:ti.leo@example.com?subject=PyWhatsWeb%20Support
    about: Contact us directly via email for urgent issues.
